### ISSUE TITLE
Cleaner CSS=>JS constants

### ISSUE THREAD

**Issue by StefanEvanghelides** [WebDevSimplified/js-2048#1]
Hi Kyle,

This is a nice project and had some fun with it. Checking the code, I believe the following small changes could make the code cleaner and easier to follow + maintain in the future:

You define the constants `GRID_SIZE`, `CELL_SIZE` and `CELL_GAP` inside Grid.js where you then use them to set your CSS. You may already see the oddity: why not define them directly in `:root` in your CSS file?

I would also jsut fetch `--grid-size` inside the scripts.js and then just pass it as a parameter to the Grid constructor. This makes the most sense to me, but I know it's subjective :)

**Comment by WebDevSimplified** [comment]
The main reason I did this was actually because in an upgraded version of this project I create a tutorial grid that uses a different grid size so I am able to change those variables for the tutorial grid. Here is the code for it. https://github.com/WebDevSimplified/2048-daily/blob/main/src/Grid.js

**Comment by StefanEvanghelides** [comment]
Makes sense. Thanks for the answer. I'll close this issue.
